version: '3.9'

services:
  db:
    container_name: thread-db
    image: postgres
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:thread
      - POSTGRES_PASSWORD:thread

volumes:
  postgres_data:
